alkemyTech/OT-99-Server

- src/main/java/com/alkemy/ong/model/Organization.java
- src/main/java/com/alkemy/ong/repository/OrganizationRepository.java
**Summary**
1. Added Organization entity
2. Added Organization repository
**Evidence**
sql: show tables;
sql: describe organizations;
> Ot99 15 add organization entity and repo

- src/main/java/com/alkemy/ong/dto/UserRegisterRequest.java
- src/main/java/com/alkemy/ong/dto/UserRegisterResponse.java
- src/main/java/com/alkemy/ong/model/Users.java
- src/main/java/com/alkemy/ong/repository/UserRepository.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/security/filter/JwtRequestFilter.java
- src/main/java/com/alkemy/ong/security/filter/JwtTokenUtil.java
- src/main/java/com/alkemy/ong/service/UserService.java
- src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
Agrego modelo y repositorio de usuarios.
> Ot99 17 model repo users

- src/main/java/com/alkemy/ong/model/Slide.java
- src/main/java/com/alkemy/ong/repository/SlideRepository.java
(Outdated, table names should now display in uppercase)
-Created Slide entity
-Created Slide repository
> Ot99-28 Add Slide model and repo

- pom.xml
- src/main/java/com/alkemy/ong/config/SendGridConfig.java
- src/main/java/com/alkemy/ong/service/EmailService.java
- src/main/java/com/alkemy/ong/service/impl/EmailServiceImpl.java
**Summary**
1. Added SendGrid configuration
2. Added EmailService
3. Added EmailServiceImpl
4. Added SendGrid library in pom.xml
5. Updated application.propierties
**Evidence**
> Ot99 27 integrate email service

- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/dto/OrganizationDetailsResponse.java
- src/main/java/com/alkemy/ong/exception/ErrorHandler.java
- src/main/java/com/alkemy/ong/service/OrganizationService.java
- src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImp.java
- Se debe realizar una petición GET hacia ruta /organization/public
- El endpoint debe devolver solamente los campos name, image, phone y address de la organización
> OT99-23: get organization details

- src/main/java/com/alkemy/ong/controller/AuthenticationController.java
- src/main/java/com/alkemy/ong/service/EmailService.java
- src/main/java/com/alkemy/ong/service/UserService.java
- src/main/java/com/alkemy/ong/service/impl/EmailServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
Utilizar el servicio de envío de emails y el template de bienvenida para enviar un email de forma programática cuando un usuario se registre, al email que proporcionó en su registro.
- Se cambió el parametro del metodo sendEmail() en el EmailService por UserRegisterRequest ya que se adecuaba mas al requerimiento de la story.
> OT99-30: Envío de email de Bienvenida

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/dto/CategoryDtoGetAll.java
- src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
- src/main/java/com/alkemy/ong/repository/CategoryRepository.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
- src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
package mapper added,
class CategoryController added,
class CategoryMapper added,
interface CategoryService added,
class CategoryServiceImpl added,
class categoryDtoGetAll added.
class UserRepository fixed (annotation repository added)
**The get endpoints to bring all the categories works (only the names):**
> Ot99 40 category controller get all endpoint

- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/UserService.java
- src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> OT99-32-endpoint-delete-user

- src/main/java/com/alkemy/ong/controller/UserController.java
- src/main/java/com/alkemy/ong/dto/UserRegisterRequest.java
- src/main/java/com/alkemy/ong/dto/UserRegisterResponse.java
- src/main/java/com/alkemy/ong/service/UserService.java
- src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> OT99-34-upgrade-user

- src/main/java/com/alkemy/ong/controller/ActivityController.java
- src/main/java/com/alkemy/ong/dto/ActivityRequest.java
- src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/ActivityService.java
- src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
- Updated security public antmatcher as was requested
- Changed @ Service annotation to @ component annotation in user mapper as it was giving out errors
- Added Activity service and service impl
- Created Activity controller with put annotation
> OT99-51 Put Activities endpoint

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/dto/CategoryDto.java
- src/main/java/com/alkemy/ong/exception/DataAlreadyExistException.java
- src/main/java/com/alkemy/ong/exception/ErrorHandler.java
- src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
- src/main/java/com/alkemy/ong/model/Category.java
- src/main/java/com/alkemy/ong/repository/CategoryRepository.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
- src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
*Se muestra creación de una nueva categoría.
*Se muestra error al intentar crear una categoría con un nombre que ya existe.
> OT99-42-Category-Endpoint-Creation

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/dto/NewsDto.java
- src/main/java/com/alkemy/ong/model/News.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/NewsService.java
- src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> OT99-45-endpoint-search-news-by-id

- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/dto/SlideDto.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
**Summary**
1. Added SlideService interface and implementation
2. Added SlideController
3. Created GET /slides endpoint which return the image url and slide order. Also created Dto as an inner class in the repository
4. Created service method that return from database the list of slides as entitys.
**Evidence**
sql: select*from slide;
localhost:8080/slides
> Ot99 55 endpoint slide list

- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/dto/ContactDto.java
- src/main/java/com/alkemy/ong/exception/ErrorHandler.java
- src/main/java/com/alkemy/ong/mapper/ContactMapper.java
- src/main/java/com/alkemy/ong/service/ContactService.java
- src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
Error detected in UserServiceImpl that affects registration and endpoints requests (mentioned in OT99-56-Slide-get-Endpoint)
class ContactController added (with save method)
class ContactDto added
added method save in ContactService interface
method save implemented in ContactServiceImpl class
method added in ErrorHandler class (now the program show the error messages when we use  validate annotations on fields in dtos)
Error messages  when someone try to persist an invalid ContactDto:
method added in ErrorHandler Class to print the messages:
> Ot99 54 contact post endpoint

- src/main/java/com/alkemy/ong/controller/ActivityController.java
- src/main/java/com/alkemy/ong/mapper/ActivityMapper.java
- src/main/java/com/alkemy/ong/repository/ActivityRepository.java
- src/main/java/com/alkemy/ong/service/ActivityService.java
- src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
Post Creation - Activities
============================================================================
Data already exist!
=========================================================================
Changes in Security Configuration, not committed.
> OT99-50-Endpoint-Activities-Creation

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/dto/CategoryDto.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
- src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> OT99-43-endpoint-for-update-of-categorys

- src/main/java/com/alkemy/ong/controller/AuthenticationController.java
- src/main/java/com/alkemy/ong/model/Users.java
- src/main/java/com/alkemy/ong/service/UserService.java
- src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
First: Login 
=====================================================================================
Logged as Admin
===============================================================================
====================================================================================
Logged as User
=================================================================================
> OT99-36-Endpoint-Get/auth/me-User

- src/main/java/com/alkemy/ong/dto/UserRegisterResponse.java
- src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
**Summary**
1. Added String jwt field in UserRegisterResponse
2. Created methods to create jwt and map the dto
**Evidence**
> Ot99 14 return token to registered user

- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
----- UPDATE -----
Deleted files cannot be deleted again as well
----------
-Added @ component to Organization Mapper
-Added path to admin
- Added Slide Service
-Added Slide ServiceImpl
-Added Slide controller
-Added delete Slide to slide controller
> Ot99-59-Add delete slide

- pom.xml
- src/main/java/com/alkemy/ong/config/AmazonS3Config.java
- src/main/resources/application.properties
- src/main/resources/application.yml
==============================Post  Upload image================================
=============================url response =========================================
===========================Controller and Service created as a test, but not committed===============
> OT99-38-Setup-Amazon-S3-Sdk

- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/dto/NewsDto.java
- src/main/java/com/alkemy/ong/dto/NewsDtoPersist.java
- src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
- src/main/java/com/alkemy/ong/mapper/NewsMapper.java
- src/main/java/com/alkemy/ong/model/News.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/NewsService.java
- src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
Conflicts with main resolved
methods save and update addeds in NewsController,NewsService, NewsServiceImpl
class created NewsMapper 
method added in CategoryMapper
added endpoints in SecurityConfiguration
added Class NewsDtoPersist with validations
We modify the rol of the actual User:
Scenarios prohibited:
Using save endpoint as Rol USER:
Using update endpoint as Rol USER:
> Ot99 46 47 creation update news

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
- src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
==========================Delete 4===============================================
==============================Get 4 ============================================
===============================Delete 100 =====================================
=============================Delete 4(after first delete)============================
> OT99-44-Delete-Category-Endpoint

- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/dto/TestimonialRequest.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
- src/main/java/com/alkemy/ong/repository/TestimonialRepository.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/TestimonialService.java
- src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
- Added Testimonial service and impl,
- Added Testimonials controller
- Added function to create testimonial
> Ot99 65 post testimonial

- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/dto/TestimonialRequest.java
- src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/TestimonialService.java
- src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
-Added put testimonials to controller and added it to security config
-Deleted "creation Date" from Testimonial Request as its data was mostly hard-coded, therefore, I edited previously created Save testimonial
> Ot99-66-Put-Testimonial

- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/email/MailMessage.java
- src/main/java/com/alkemy/ong/service/ContactService.java
- src/main/java/com/alkemy/ong/service/EmailService.java
- src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/EmailServiceImpl.java
Nico agrego el servicio para enviar un mail de agradecimiento cuando se registra un nuevo contacto, pero el sistema no valida que el mail del contacto ya se encuentre registrado.
> OT99-62-send-email-for-registration-of-contact

- src/main/java/com/alkemy/ong/config/AmazonS3Config.java
- src/main/java/com/alkemy/ong/service/ImageService.java
- src/main/java/com/alkemy/ong/service/impl/ImageServiceImpl.java
**Summary** 
1. Created Image Service interface and impl.
2. Added getters in AmazonS3Config
**Evidence**
> Ot99 39 upload images service

- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/dto/CommentDto.java
- src/main/java/com/alkemy/ong/mapper/CommentMapper.java
- src/main/java/com/alkemy/ong/model/Comment.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
Class CommentController added with method getAll
Class CommentMapper added
method getAll added in CommentService and implemented in CommentServiceImpl
attribute date added in Comment model
added /comments route to SecurityConfiguration (2 fix introduced in admin Endpoints)
Prohibited Scenario (user logged with role user):
Permited Scenario (User logged with role admin) comments with DESC order :
> Ot99 75 comment list endpoint

- src/main/java/com/alkemy/ong/dto/OrganizationDetailsResponse.java
- src/main/java/com/alkemy/ong/dto/OrganizationRequest.java
POST
=======================================================================================
GET
> OT99-64-Modify-Endpoint-Organizations

- src/main/java/com/alkemy/ong/model/Organization.java
> OT99-63-Add-Info-Organizations

- src/main/java/com/alkemy/ong/controller/ContactController.java
- src/main/java/com/alkemy/ong/dto/ContactDto.java
- src/main/java/com/alkemy/ong/mapper/ContactMapper.java
- src/main/java/com/alkemy/ong/service/ContactService.java
- src/main/java/com/alkemy/ong/service/impl/ContactServiceImpl.java
**Summary**
1. Added getContact methods in  controller, service and service impl.
2. Changed ConctactDto and ContactMapper's phone field from double to long. That's because as a double field the endpoint return wasn't as expected.
**Evidence**
with double:
changed to long:
check if the other endpoint work's well:
the return of the getContacts on this last contact:
> Ot99 61 endpoint to list contacts

- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/dto/MemberDto.java
- src/main/java/com/alkemy/ong/mapper/MemberMapper.java
- src/main/java/com/alkemy/ong/model/Member.java
- src/main/java/com/alkemy/ong/repository/MemberRepository.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
POST: Member created!
=====================================================================================
Not again!. Member already exists!.
===================================================================================
Name is mandatory!
=====================================================================================
Name can't be null!
> OT99-69-Members-Endpoint-Creation

- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/model/Member.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
**Summary**
1. Created MemberRepository, MemberService, MemberServiceImpl. 
2. Added enpoints in security config.
3. Formated code.
**Evidence**
sql before deleting:
get all members before deleting:
deleting:
sql after deleting:
get all members after deleting:
trying deleting the same id:
not commited methods:
> Ot99 70 endpoint delete members

- src/main/resources/application.properties
- src/main/resources/data.sql
- Added Seed data in root that populates database.organization. 
- Created using drive data, took some liberties at the time of writing welcome text and about us text.
-----UPDATE----
Changed insert to REPLACE and hardcoded our org value id to 1.
> Ot99-52 Add Seed Organization Data

- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/model/Member.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
> OT99-68-list-of-members

- src/main/java/com/alkemy/ong/controller/OrganizationController.java
- src/main/java/com/alkemy/ong/dto/OrganizationDetailsResponse.java
- src/main/java/com/alkemy/ong/dto/OrganizationResponse.java
- src/main/java/com/alkemy/ong/dto/SlideDtoGet.java
- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/mapper/SlideMapper.java
- src/main/java/com/alkemy/ong/repository/SlideRepository.java
- src/main/java/com/alkemy/ong/service/OrganizationService.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImp.java
- src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
modifications introduced:
added list of slides dto in OrganizationResponse class.
method getOrganizationDetails in class OrganizationController,OrganizationService,OrganizationServiceImpl.
method toOrganizationResponse added in OrganizationMapper (previously was present in OrganizationResponse)
method getAllSlides added and implemented in SlideService and SlideServiceImpl.
method findAllByOrganizationId added and query by order added, in SlideRepository
method toSlideDtoGetList added in SlideMapper.
constructor added in SlideDtoGet class because the implementation of a lambda expression.
> Ot99 60 get slides by organization

- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/dto/CommentDtoResponse.java
- src/main/java/com/alkemy/ong/dto/CommentDtoSave.java
- src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> OT99-76-create-comments

- src/main/java/com/alkemy/ong/service/ImageService.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- src/main/java/com/alkemy/ong/service/impl/ImageServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
https://trello.com/c/fI820Pq0
Relocated base 64 to multipart converter to image service
> OT99-HOTFIX Relocate converter to image Service imp

- src/main/java/com/alkemy/ong/controller/NewsController.java
- src/main/java/com/alkemy/ong/repository/CommentRepository.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- src/main/java/com/alkemy/ong/service/NewsService.java
- src/main/java/com/alkemy/ong/service/impl/ActivityServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
- src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
- Fixed small grammar details
- Added list comments by news id
> Ot99 79 list news comments

- src/main/java/com/alkemy/ong/controller/CategoryController.java
- src/main/java/com/alkemy/ong/dto/CategoryPageDto.java
- src/main/java/com/alkemy/ong/dto/PageDto.java
- src/main/java/com/alkemy/ong/repository/CategoryRepository.java
- src/main/java/com/alkemy/ong/service/CategoryService.java
- src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
**Summary**
1. Added findAll method in repo with int parameter and page return.
2. Modified methods in service layer findAll that return CategoryPageDto and recieve int parameter.
3. Created CategoryPageDto.
4. Modifed endpoint in controller.
**Evidence**
DATABASE: 
GET:/categories?page=0
GET:/categories?page=1
GET:/categories?page=2
GET:/categories?page=3
> Ot99 80 add pagination to categories

- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/repository/MemberRepository.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
=========Solicitamos que se muestre la info de a 2=========================
==============Solicitamos que se muestre la info de a 5====================
> OT99-82-Add-paging-members

- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/dto/PageDto.java
- src/main/java/com/alkemy/ong/dto/TestimonialDto.java
- src/main/java/com/alkemy/ong/dto/TestimonialRequest.java
- src/main/java/com/alkemy/ong/exception/ErrorHandler.java
- src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
- src/main/java/com/alkemy/ong/repository/TestimonialRepository.java
- src/main/java/com/alkemy/ong/service/TestimonialService.java
- src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
- src/main/resources/data.sql
Pagination functionality added at the moment to recover Testimonials
method getPage added in TestimonialController class
method getPage added and implemented in TestimonialService and TestimonialServiceImpl classes
Refactorin in Testimonial mapper: method toPageDto, toTestimonialDtoList, updateEntityWithoutName added
illegalArgumentException added in ErrorHandler class
data.sql  REPLACE INTO were replace by INSERT IGNORE INTO
variable updateAt deleted in TestimonialRequest class
the updates of dates at the moment of creation and update were move to TestimonialMapper
SAVE:
UPDATE:
NOW THERE IS NO CONFLICT IF THE NAME IS THE SAME:
> Ot99 83 testimonials pagination

- src/main/java/com/alkemy/ong/controller/AuthenticationController.java
- src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
- src/test/java/com/alkemy/ong/test/AuthenticationControllerTest.java
Tests login, register, and data added in AuthenticationControllerTest class
> Ot99 96 test authentication

- src/test/java/com/alkemy/ong/organization/OrganizationControllerTest.java
Added ONG controller testing
-checks for id not found
-checks for invalid parameters
-checks for authorization and authentication
> Ot99-92-Ong-Test Test Ong controller

- pom.xml
- src/test/java/com/alkemy/ong/ActivityControllerTests.java
- src/test/java/com/alkemy/ong/organization/OrganizationControllerTest.java
**Summary**
1. Added dependencies that work with all the merged tests and activities test.
2. added missing import in organization test
3. added activities tests
**Evidence**
> Ot99 94 testing activities controller

- src/test/java/com/alkemy/ong/test/NewsControllerTest.java
> OT99-93-Test-Endpoints-News

- src/test/java/com/alkemy/ong/MemberControllerTest.java
Todo Ok!
Sólo por un pequeño 201, que devuelve, pero es el mismo resultado.
> OT99-91-Test-Endpoints-Members
